### ISSUE TITLE
"sudo ./BUILD-DOCKER-IMAGE.sh"failed

### ISSUE THREAD

**Issue by xiu-ccc** [o2as/ur-o2as#5]
Dear Author 
I tried to reproduce your work in Ubuntu 16.04, but there were some errors in build the docker image.

Steps:
git submodule update --init
cd ~/ur-o2as/ && sudo ./SETUP-DEVEL-MACHINE.sh
sudo ./BUILD-DOCKER-IMAGE.sh

In dockerfile, I follow the instructions and the following problems appear：

question1：I only have one graphics card. Can nccl not be installed
step：
RUN git clone https://github.com/NVIDI#A/nccl.git && cd nccl && make -j install && cd .. && rm -rf nccl \
	&& mkdir build && cd build \
	&& cmake -DUSE_CUDNN=1 -DUSE_NCCL=1 .. \
	&& make -j"$(nproc)"

back:
In file included from include/core.h:57:0,
                 from include/debug.h:10,
                 from include/checks.h:10,
                 from include/alloc.h:11,
                 from include/gdrwrap.h:148,
                 from misc/gdrwrap.cc:7:
include/param.h: In function 'void setEnvFile(const char*)':
include/param.h:34:43: error: 'strncpy' was not declared in this scope
     strncpy(envVar, line, std::min(1023,s));
                                           ^
In file included from include/channel.h:9:0,
                 from channel.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from proxy.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from transport.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/channel.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/channel.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from include/enqueue.h:10:0,
                 from enqueue.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from transport/shm.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from enqueue.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
In file included from include/group.h:11:0,
                 from group.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
make[1]: *** [/opt/caffe/nccl/build/obj/proxy.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/proxy.o' failed
In file included from include/channel.h:9:0,
                 from init.cc:8:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
enqueue.cc:798:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph) {
                                                ^
In file included from misc/argcheck.cc:8:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
enqueue.cc:827:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph) {
                                                      ^
enqueue.cc: In function 'ncclResult_t ncclEnqueueCheck(ncclInfo*)':
enqueue.cc:891:5: error: 'cudaGraph_t' was not declared in this scope
     cudaGraph_t graph;
     ^
In file included from include/core.h:54:0,
                 from include/transport.h:13,
                 from include/comm.h:10,
                 from include/enqueue.h:10,
                 from enqueue.cc:7:
enqueue.cc:893:39: error: 'graph' was not declared in this scope
     NCCLCHECK(ncclGetCudaGraph(comm, &graph));
                                       ^
include/checks.h:65:22: note: in definition of macro 'NCCLCHECK'
   ncclResult_t res = call; \
                      ^
enqueue.cc:900:46: error: 'graph' was not declared in this scope
       NCCLCHECK(ncclCudaGraphHostSetup(comm, graph));
                                              ^
include/checks.h:65:22: note: in definition of macro 'NCCLCHECK'
   ncclResult_t res = call; \
                      ^
In file included from group.cc:9:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
group.cc: In function 'ncclResult_t ncclGroupEnd()':
group.cc:167:3: error: 'cudaGraph_t' was not declared in this scope
   cudaGraph_t* graphs = NULL;
   ^
group.cc:167:16: error: 'graphs' was not declared in this scope
   cudaGraph_t* graphs = NULL;
                ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/transport.o] Error 1
In file included from init.cc:16:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/misc/gdrwrap.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/misc/gdrwrap.o] Error 1
In file included from transport/p2p.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
init.cc: In function 'ncclResult_t commAlloc(ncclComm**, int, int)':
init.cc:277:9: error: 'struct ncclComm' has no member named 'lastSetupNode'
   comm->lastSetupNode = NULL;
         ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport/shm.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/transport/shm.o] Error 1
In file included from transport/net_socket.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/misc/argcheck.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/misc/argcheck.o] Error 1
In file included from transport/coll_net.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/enqueue.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/enqueue.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/group.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/group.o] Error 1
In file included from transport/net.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport/p2p.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/transport/p2p.o] Error 1
In file included from include/enqueue.h:10:0,
                 from collectives/broadcast.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from include/enqueue.h:10:0,
                 from collectives/sendrecv.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from include/enqueue.h:10:0,
                 from collectives/all_gather.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
make[1]: *** [/opt/caffe/nccl/build/obj/init.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/init.o' failed
In file included from collectives/broadcast.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
In file included from include/enqueue.h:10:0,
                 from collectives/all_reduce.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from graph/connect.cc:7:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from collectives/all_gather.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport/net_socket.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/transport/net_socket.o] Error 1
In file included from collectives/sendrecv.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport/coll_net.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/transport/coll_net.o] Error 1
In file included from graph/paths.cc:10:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from graph/topo.cc:10:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from graph/tuning.cc:9:0:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from collectives/all_reduce.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
In file included from include/enqueue.h:10:0,
                 from collectives/reduce.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from include/enqueue.h:10:0,
                 from collectives/reduce_scatter.cc:7:
include/comm.h:160:3: error: 'cudaGraphNode_t' does not name a type
   cudaGraphNode_t lastSetupNode;
   ^
In file included from collectives/reduce.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
In file included from collectives/reduce_scatter.cc:7:0:
include/enqueue.h:27:48: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclGetCudaGraph(ncclComm_t comm, cudaGraph_t* graph);
                                                ^
include/enqueue.h:28:54: error: 'cudaGraph_t' has not been declared
 ncclResult_t ncclCudaGraphHostSetup(ncclComm_t comm, cudaGraph_t graph);
                                                      ^
make[1]: *** [/opt/caffe/nccl/build/obj/transport/net.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/transport/net.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/graph/tuning.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/graph/tuning.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/all_gather.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/all_gather.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/broadcast.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/broadcast.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/sendrecv.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/sendrecv.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/graph/paths.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/graph/paths.o' failed
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/all_reduce.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/all_reduce.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/graph/connect.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/graph/connect.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/reduce_scatter.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/reduce_scatter.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/collectives/reduce.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/collectives/reduce.o] Error 1
Makefile:111: recipe for target '/opt/caffe/nccl/build/obj/graph/topo.o' failed
make[1]: *** [/opt/caffe/nccl/build/obj/graph/topo.o] Error 1
××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
question2：Extension 'ajshort.ros' not found.
step:
RUN code --install-extension ms-python.python --user-data-dir=/root/.vscode/ \
	&& code --install-extension ms-vscode.cpptools --user-data-dir=/root/.vscode/ \
	&& code --install-extension ms-azuretools.vscode-docker --user-data-dir=/root/.vscode/ \
	&& code --install-extension streetsidesoftware.code-spell-checker --user-data-dir=/root/.vscode/ \
	&& code --install-extension eamodio.gitlens --user-data-dir=/root/.vscode/ \
	&& code --install-extension ajshort.ros --user-data-dir=/root/.vscode/ \
	&& code --install-extension ajshort.msg --user-data-dir=/root/.vscode/

back:
RUN code --install-extension ms-python.python --user-data-dir=/root/.vscode/ 	&& code --install-extension ms-vscode.cpptools --user-data-dir=/root/.vscode/ 	&& code --install-extension ms-azuretools.vscode-docker --user-data-dir=/root/.vscode/ 	&& code --install-extension streetsidesoftware.code-spell-checker --user-data-dir=/root/.vscode/ 	&& code --install-extension eamodio.gitlens --user-data-dir=/root/.vscode/ 	&& code --install-extension ajshort.ros --user-data-dir=/root/.vscode/ 	&& code --install-extension ajshort.msg --user-data-dir=/root/.vscode/
 ---> Running in 685139c4f6cc
Installing extensions...
Installing extension 'ms-python.python' v2021.5.842923320...
(node:12) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-python.python' v2021.5.842923320 was successfully installed.
Installing extensions...
Installing extension 'ms-vscode.cpptools' v1.4.0...
(node:30) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-vscode.cpptools' v1.4.0 was successfully installed.
Installing extensions...
Installing extension 'ms-azuretools.vscode-docker' v1.13.0...
(node:48) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-azuretools.vscode-docker' v1.13.0 was successfully installed.
Installing extensions...
Installing extension 'streetsidesoftware.code-spell-checker' v1.10.2...
(node:66) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'streetsidesoftware.code-spell-checker' v1.10.2 was successfully installed.
Installing extensions...
Installing extension 'eamodio.gitlens' v11.4.1...
(node:84) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'eamodio.gitlens' v11.4.1 was successfully installed.
Installing extensions...
Extension 'ajshort.ros' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: ajshort.ros
ERROR: Service 'ur-o2as' failed to build: The command '/bin/sh -c code --install-extension ms-python.python --user-data-dir=/root/.vscode/ 	&& code --install-extension ms-vscode.cpptools --user-data-dir=/root/.vscode/ 	&& code --install-extension ms-azuretools.vscode-docker --user-data-dir=/root/.vscode/ 	&& code --install-extension streetsidesoftware.code-spell-checker --user-data-dir=/root/.vscode/ 	&& code --install-extension eamodio.gitlens --user-data-dir=/root/.vscode/ 	&& code --install-extension ajshort.ros --user-data-dir=/root/.vscode/ 	&& code --install-extension ajshort.msg --user-data-dir=/root/.vscode/' returned a non-zero code: 1

××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
question3:faild to fetch http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/dists/xenial/main/binary-amd64/Packages  403  Forbidden
step:
RUN rm -f /etc/apt/sources.list.d/realsense-public.list
RUN echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main' | tee /etc/apt/sources.list.d/realsense-public.list
RUN apt-key adv --keyserver keys.gnupg.net --recv-key C8B3A55A6F3EFCDE
RUN sudo apt-get update
RUN apt-get install -y --no-install-recommends \
	librealsense2-dkms \
	librealsense2-utils \
	librealsense2-dev \
	librealsense2-dbg

back:
 RUN sudo apt-get update
 ---> Running in 6d3664c29e70
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:2 http://packages.ros.org/ros/ubuntu xenial InRelease [4692 B]
Get:3 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:5 https://packages.microsoft.com/repos/vscode stable InRelease [3958 B]
Ign:6 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial InRelease
Get:7 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages [262 kB]
Get:8 http://packages.ros.org/ros/ubuntu xenial/main i386 Packages [625 kB]
Ign:9 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial Release
Get:4 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages [854 kB]
Ign:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [2051 kB]
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Get:15 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [1442 kB]
Ign:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
Get:18 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [15.9 kB]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/restricted i386 Packages [15.9 kB]
Get:20 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [984 kB]
Get:21 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [833 kB]
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Get:22 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [8820 B]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [9052 B]
Get:24 http://archive.ubuntu.com/ubuntu xenial/main i386 Packages [1552 kB]
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Get:25 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial/restricted i386 Packages [14.5 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Ign:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Ign:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Ign:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Ign:28 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Get:29 http://archive.ubuntu.com/ubuntu xenial/universe i386 Packages [9804 kB]
Ign:30 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Err:10 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main amd64 Packages
  403  Forbidden
Ign:12 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main i386 Packages
Get:31 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [164 B]
Ign:14 http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial/main all Packages
Get:32 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release [164 B]
Get:33 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [164 B]
Get:34 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release.gpg [164 B]
Get:35 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:36 http://archive.ubuntu.com/ubuntu xenial/multiverse i386 Packages [172 kB]
Get:37 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2559 kB]
Ign:38 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
Get:39 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [122 kB]
Get:38 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [716 kB]
Get:40 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [1912 kB]
Get:41 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [16.4 kB]
Get:42 http://archive.ubuntu.com/ubuntu xenial-updates/restricted i386 Packages [16.4 kB]
Get:43 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1544 kB]
Get:44 http://archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [1377 kB]
Get:45 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [26.2 kB]
Get:46 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse i386 Packages [24.6 kB]
Get:47 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [10.9 kB]
Get:48 http://archive.ubuntu.com/ubuntu xenial-backports/main i386 Packages [10.9 kB]
Get:49 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [12.7 kB]
Get:50 http://archive.ubuntu.com/ubuntu xenial-backports/universe i386 Packages [12.2 kB]
Fetched 39.2 MB in 16s (2391 kB/s)
Reading package lists...
W: The repository 'http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial Release' does not have a Release file.
E: Failed to fetch http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'ur-o2as' failed to build: The command '/bin/sh -c sudo apt-get update' returned a non-zero code: 100

×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
question4:open http://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar show 404
step:
RUN wget -O - http://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar \
	| tar xf - \
	&& ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run \
    && rm ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run
ENV PHOXI_CONTROL_PATH /opt/PhotoneoPhoXiControl
ENV PATH ${PATH}:${PHOXI_CONTROL_PATH}/bin
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${PHOXI_CONTROL_PATH}/API/lib
ENV CPATH ${CPATH}:${PHOXI_CONTROL_PATH}/API/include
ENV PhoXi_DIR ${PHOXI_CONTROL_PATH}
COPY ./docker/cmake/PhoXiConfig.cmake /opt/PhotoneoPhoXiControl/

back:
RUN wget -O - http://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar 	| tar xf - 	&& ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run     && rm ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run
 ---> Running in 1d9516fe54b2
--2021-06-08 13:47:28--  http://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar
Resolving www.photoneo.com (www.photoneo.com)... 37.9.175.8
Connecting to www.photoneo.com (www.photoneo.com)|37.9.175.8|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar [following]
--2021-06-08 13:47:35--  https://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar
Connecting to www.photoneo.com (www.photoneo.com)|37.9.175.8|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-08 13:47:42 ERROR 404: Not Found.

tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
ERROR: Service 'ur-o2as' failed to build: The command '/bin/sh -c wget -O - http://www.photoneo.com/files/PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.tar 	| tar xf - 	&& ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run     && rm ./PhotoneoPhoXiControl-1.1.32-Ubuntu16.04-LTS-64-gcc5.4.run' returned a non-zero code: 2
